name: Document package

on:
  push:
    paths:
      - src/**
      - .github/workflows/document.yaml
    branches:
      - 'main'
      - 'master'
  
jobs:

  document: 

    runs-on: ubuntu-latest

    name: "Document package"

    steps:

      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install packages
        run: |
          pip install -r requirements-dev.txt

      - name: Install package
        run: pip install .

      - name: Generate documentation
        run: |
          pdoc --html --output-dir docs FuzzyMath

      - name: Set GIT
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Github Action"

      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN  }}
          publish_branch: gh-pages
          publish_dir: ./docs/FuzzyMath
