name: Release package to PiPy

on:
  push:
    branches:
      - 'main'
      - 'master'
  
jobs:

  release: 

    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write

    name: "Release package to PiPy"

    steps:

      - uses: actions/checkout@v4

      - name: Install pandoc
        run: |
          sudo apt install -y pandoc

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Python install required packages
        run: |
            pip install -r requirements-dev.txt

      - name: Translate Readme.md to rst
        run: |
          pandoc --to=rst -o Readme.rst Readme.md
          echo "-----"
          cat Readme.rst

      - name: Release
        run: |
          python3 -m build
      
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
    
      - name: Upload WHL file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: FuzzyMath
          path: dist/FuzzyMath-*.whl
      
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/FuzzyMath-*.whl